# AppVeyor for Boost.Astronomy
#
# Copyright 2016, 2017 Peter Dimov
# Copyright 2018 Mateusz Loskot <mateusz at loskot dot net>
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
version: 1.0.{build}-{branch}

# Current Boost.Astronomy develop branch (future Boost 1.68) requires C++11
# Since VS2017, MSVC default is /std:c++14, so no explicit switch is required.
image: Visual Studio 2017

platform: x64

shallow_clone: true

environment:
  matrix:
    - TOOLSET: msvc-14.0
      ARCH: x86_64
      VARIANT: debug
      CXXSTD: 11
      TEST_HEADERS: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - TOOLSET: msvc-14.0
      ARCH: x86_64
      VARIANT: release
      CXXSTD: 11
      TEST_HEADERS: 1
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

cache:
  - c:\tools\vcpkg\installed\

install:
  # FIXME: To be removed https://help.appveyor.com/discussions/problems/13000-cmake_toolchain_filevcpkgcmake-conflicts-with-cmake-native-findboostcmake"
  - ps: 'Write-Host "Installing latest vcpkg.cmake module" -ForegroundColor Magenta'
  - appveyor DownloadFile https://raw.githubusercontent.com/Microsoft/vcpkg/master/scripts/buildsystems/vcpkg.cmake -FileName "c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - if %ARCH% == x86 ( set "TRIPLET=x86-windows" ) else ( set "TRIPLET=x64-windows" )
  - if %ARCH% == x86 ( set AM=32 ) else ( set AM=64 )
  - vcpkg --triplet %TRIPLET% install libjpeg-turbo libpng tiff
  - if NOT DEFINED GENERATOR set PATH=c:\Tools\vcpkg\installed\%TRIPLET%\bin;%PATH%
  - if NOT DEFINED GENERATOR set VCPKG_I=C:\Tools\vcpkg\installed\%TRIPLET%\include
  - if NOT DEFINED GENERATOR set VCPKG_L=C:\Tools\vcpkg\installed\%TRIPLET%\lib
  - if NOT DEFINED GENERATOR set LIBPNG_NAME=libpng16
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master

before_build:
  - cd ..
  - bash -c '$APPVEYOR_BUILD_FOLDER/.ci/get-boost.sh $APPVEYOR_REPO_BRANCH $APPVEYOR_BUILD_FOLDER'
  - cd boost-root
  - cmd /c bootstrap
  - .\b2 headers > NUL
  - if DEFINED GENERATOR .\b2 address-model=%AM% toolset=%TOOLSET% variant=%VARIANT% cxxstd=%CXXSTD% --with-filesystem --with-test stage

build: on

build_script:
  - if NOT DEFINED GENERATOR b2 address-model=%AM% toolset=%TOOLSET% variant=%VARIANT% cxxstd=%CXXSTD% libs/astronomy/test
  - if DEFINED GENERATOR cd libs\astronomy && md build && cd build
  - if DEFINED GENERATOR cmake -G "%GENERATOR%" -DCMAKE_CXX_STANDARD=%CXXSTD% -DBoost_DETAILED_FAILURE_MSG=ON -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - if DEFINED GENERATOR cmake --build . --config %CMAKE_CONFIG %

test_script:
  - if DEFINED GENERATOR ctest -V --output-on-failure -C %VARIANT%
